deployment:
  enabled: true
  replicaCount: 3

cronjob:
  enabled: true
  schedule: "*/30 * * * *"

service:
  type: LoadBalancer # external-facing

ingress:
  enabled: true
  hosts:
    - host: shop-stg.example.com
      paths:
        - path: /
          pathType: Prefix

hpa:
  enabled: false

resources:
  requests:
    cpu: 100
    memory: 256
  limits:
    cpu: 1000
    memory: 1024

config:
  enabled: true
  data:
    APP_ENV: "stg"
