{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop_backend.fullname" . | default .Release.Name }}-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
