{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop_backend.fullname" . | default .Release.Name }}
  labels:
    {{- include "shop_backend.name" . | default "shop_backend" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "shop_backend.name" . | default "shop_backend" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- end }}
